### ISSUE TITLE
Daemon doesn't know what to do with events from tagged packages

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#16]
How de we handle events from packages that check out an specific commit or tag? In principle, I think we should ignore those but tags may change and commits may be removed. Do we ignore those cases?

**Comment by doudou** [comment]
> Do we ignore those cases?

I think we should. Even Travis has issues in these cases.

**Comment by g-arjones** [comment]
Already implemented.. Hey, if you could have a final look at the daemon that would be great. I will fix a test that's failing today and try to make the buildconf's tests pass (by removing orocos.rb tests). Then, if I get the time, deploy and run on the server

**Comment by doudou** [comment]
Sure. Since you hadn't requested a new review, I thought you were not done

**Comment by g-arjones** [comment]
Ah.. Yeah, I forgot we've agreed on that..
