### ISSUE TITLE
does not merge the buildconf's master into automatically created branches

### ISSUE THREAD

**Issue by doudou** [rock-core/autoproj-daemon#25]
Scenario:
- a pull request is created on a package
- the daemon creates an autobuild/FOOBAR branch
- the buildconf master is modified to remove an override, the corresponding branch is deleted
- autobuild/FOOBAR should be reset on top of the new master, or it will fail because of the missing branch

**Comment by g-arjones** [comment]
Something similar should be done with package sets.. Building an outdated package set with an up-to-date buildconf master will most likely fail

**Comment by doudou** [comment]
> Something similar should be done with package sets.. Building an outdated package set with an up-to-date buildconf master will most likely fail

True. Maybe we should track pull/<ID>/merge instead of pull/<ID>/head which would be testing the actual result of merging the PR instead of the PR itself ?

The buildconf is different as it is not a PR, but a branch that the daemon is managing itself.

>  @g-arjones g-arjones added the enhancement label 1 hour ago 

I think it should be `bug`. It has really bad consequences: any removal  or change of an override will make all current in-flight PRs fail forever.

**Comment by g-arjones** [comment]
> Maybe we should track pull//merge instead of pull//head

Yeah, I thought about that first and didn't do it because we wouldn't be able to build PRs that have conflicts with the base branch but maybe that's not even a bad thing. Let's do that 👍 

>  think it should be bug

Agreed

**Comment by g-arjones** [comment]
I started to fix this and came to a point I had to decide whether the daemon should trigger a build (in addition to "rebasing" the auto generated branches) on all tracked PRs... In principle I think this might be a very expensive operation and probably not a good idea... @doudou thoughts?

**Comment by doudou** [comment]
I would try triggering at first ... I don't think it's going too problematic (expensive-wise) for us at this stage.
