### ISSUE TITLE
Pull Request close events are missed (rarely)

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#30]
So, I've managed to track this down to a single PR where this would happen (orocos/orocos_kinematics_dynamics#193)...

It seems like a bug in github's because, for some reason, this particular PR's close event is not returned in the organization's event feed. Script to reproduce:

```ruby
require 'octokit'

client = Octokit::Client.new(access_token: 'VALID_API_KEY_HERE')
client.auto_paginate = true

user_events = client.organization_events('orocos').map(&:to_hash)
pull_request_events = user_events.select { |e| e[:type] == 'PullRequestEvent' }
repo_events = pull_request_events.select { |e| e[:payload][:pull_request][:base][:repo][:name] == 'orocos_kinematics_dynamics'}
bogus_pr_events = repo_events.select { |e| e[:payload][:pull_request][:number] == 193 }

bogus_pr_events.each do |e|
    puts "#{e[:payload][:pull_request][:base][:user][:login]}/"\
         "#{e[:payload][:pull_request][:base][:repo][:name]}#"\
         "#{e[:payload][:pull_request][:number]} "\
         "(branch: #{e[:payload][:pull_request][:base][:ref]}, state: #{e[:payload][:pull_request][:state]})"
end
```

Output:

```console
arjones@tidewise:~/dev/autoproj-daemon$ bundle exec ruby bug.rb 
orocos/orocos_kinematics_dynamics#193 (branch: master, state: open)
```

Surprisingly enough, if we use the `Octokit::Client#user_events` API we get the lost PR close event. The problem is that `#user_events` does not return push events and we obviously need those.

```ruby
require 'octokit'

client = Octokit::Client.new(access_token: 'VALID_API_KEY_HERE')
client.auto_paginate = true

user_events = client.user_events('orocos').map(&:to_hash) # <-- this returns the lost event
pull_request_events = user_events.select { |e| e[:type] == 'PullRequestEvent' }
repo_events = pull_request_events.select { |e| e[:payload][:pull_request][:base][:repo][:name] == 'orocos_kinematics_dynamics'}
bogus_pr_events = repo_events.select { |e| e[:payload][:pull_request][:number] == 193 }

bogus_pr_events.each do |e|
    puts "#{e[:payload][:pull_request][:base][:user][:login]}/"\
         "#{e[:payload][:pull_request][:base][:repo][:name]}#"\
         "#{e[:payload][:pull_request][:number]} "\
         "(branch: #{e[:payload][:pull_request][:base][:ref]}, state: #{e[:payload][:pull_request][:state]})"
end
```

Output:

```console
arjones@tidewise:~/dev/autoproj-daemon$ bundle exec ruby bug.rb 
orocos/orocos_kinematics_dynamics#193 (branch: master, state: closed)
orocos/orocos_kinematics_dynamics#193 (branch: master, state: open)
```

The only (crappy) solutions I can think of is to verify that a PR really is open before actually handling the open event, which means we perform an extra API call for each open event; or merging the returned feeds from `#user_events` and `#organization_events`, which maybe a bit less crappy workaround but still terrible IMHO.

Thoughts, please?

**Comment by doudou** [comment]
I think the best course of action would be to open an issue on GH itself to complain about the behavior.

**Comment by doudou** [comment]
One thing I don't get is how this would trigger a boot loop on our master branch ?

**Comment by g-arjones** [comment]
> I think the best course of action would be to open an issue on GH itself to complain about the behavior.

Sure.. But we probably need a workaround in the meantime as wel..

> One thing I don't get is how this would trigger a boot loop on our master branch ?

Hmmm.. Did not see that behavior in the logs and did not happen while I were testing.. What I noticed was that the daemon would delete the buildconf branch at startup (because the PR is closed) and then recreate and test it again once it starting polling events. Over and over..

I will check older logs and try to reproduce

**Comment by doudou** [comment]
> Hmmm.. Did not see that behavior in the logs and did not happen while I were testing.. What I noticed was that the daemon would delete the buildconf branch at startup (because the PR is closed) and then recreate and test it again once it starting polling events. Over and over..

That's the build loop, since the daemon gets restarted each time there's a buildconf change. No ?

However, there was also a loop on wetpaint:master (builds 247 to 258). I don't think it can be explained by this behavior, can it ?

**Comment by g-arjones** [comment]
> the daemon gets restarted each time there's a buildconf change. No ?

Only on changes to buildconf's mainline. Only mainline changes trigger updates (and restarts).

>  I don't think it can be explained by this behavior, can it ?

Nope.. That's the other thing I have to look in the logs (which I didn't notice was happening)

**Comment by g-arjones** [comment]
OK.. So, after investigating this for a while now I found the master build loop in the logs:

```
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
Push detected on ros/urdfdom, branch: master
```

Unfortunately, given the high traffic in ros' github organization we cannot see the events that might have triggered this in the organization event feed anymore (only the 300 most recent are returned). Looking into the repository event feed instead I cannot see anything that would explain this. 

By looking at the code, [the only way a push event is handled is if the push's head sha is different from the current checked out head sha](https://github.com/rock-core/autoproj-daemon/blob/a63f192ab1a9ef921f360b75fa23a854967899b9/lib/autoproj/daemon/github_watcher.rb#L138). So, the best we can do is speculate about what could have happened. My bet is that either:

1. A push event was lost;
2. Commits were added in a different order than what was reported by the API

Either way, there's not much we can do about it. Regarding the missing 'close PR event', I have opened an issue in octokit's repository: https://github.com/octokit/octokit.rb/issues/1182. I have sent pretty much the same thing to Github's support email as well (didn't find any other channel to report a possible bug).

We still have to decide what to do in the meantime. Thoughts?

**Comment by doudou** [comment]
> Thoughts?

For the GH bug: as far as I understood, there should be low impact of that particular bug, since the daemon does not restart this often. In which case, I'd leave it be on our side.

For the push bug: the right course of action would be to add code to autoproj-daemon that would allow to debug the issue should it reappear, as e.g. the HEAD ID of the push as well as the current HEAD

This would allow us to track what happened on the autoproj side using the autoproj log (which currently shows that autoproj did not update anything during the loop, which could explain a few things ...)

**Comment by g-arjones** [comment]
> For the GH bug

It seems to be in octokit.rb, rather. If that's the case, could also explain the master build loop.

> add code to autoproj-daemon that would allow to debug

:+1: 

> currently shows that autoproj did not update anything

I remember grep'ing "resetting" ([as in "resetting branch master to..."](https://github.com/rock-core/autobuild/blob/68267462fe9058e63a6a1906dd58f7ad47f673e1/lib/autobuild/import/git.rb#L1020)) in the logs... I think autoproj did update the package.

**Comment by doudou** [comment]
> I think autoproj did update the package.

Interesting. The log shows no difference though ... Maybe it took a while for another commit to be propagated as event ? I've already seen weird behavior like that.

If it happens again, we might have to actively avoid re-processing events. Is this what happens btw ? The daemon gets events it already processed, but since the two HEAD are still different, re-triggers ?

**Comment by g-arjones** [comment]
> Maybe it took a while for another commit to be propagated as event 

Would also explain the behavior...

> The daemon gets events it already processed, but since the two HEAD are still different, re-triggers ?

Yes because it restarts to update and it doesn't keep a cache of pushes (git itself should be the "cache"). If what you are suggesting does really happen, we will probably need a cache of pushes

**Comment by doudou** [comment]
OK so ...

Got the same problem twice over the last few weeks. It was a push to mainline (no pull request), and was definitely a problem of having a SHA in the event that does not match the SHA from the actual branch.
