### ISSUE TITLE
Can't get events for some organizations

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#45]
Just noticed that the daemon is not picking up events from `rock-drivers`. @doudou Would you please confirm this on your side?

```ruby
require 'octokit'

client = Octokit::Client.new(:access_token => "YOUR API KEY") # preferably from someone that is not a member of 'rock-drivers'
client.auto_paginate = true
events = client.organization_events('rock-drivers').map(&:to_hash)

File.write('debug.txt', JSON.pretty_generate(events))
```

Using my own api key I can only get events from back in 2020-10-12, using a key from someone that is not a member of `rock-drivers` I get an empty array. Not sure if this is some kind of configuration within `rock-drivers` nor if there was a change in behavior since neither of us noticed this before.

`rock-core` seems to give the expected results in both cases...

**Comment by g-arjones** [comment]
@doudou Ping?

**Comment by doudou** [comment]
Sorry for the non-response.

With my key I do get events more recent than the one you mentioned (yesterday). The 2020-10-12 event could actually be the last event when you tested.

Using a key that has no membership indeed returns an empty array, for both rock-drivers and rock-control but *not* for rock-core. I don't see any other way than mentioning it to GitHub support and see what they say.
