### ISSUE TITLE
Daemon cannot test drafts 

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#47]
Github does not create the merged branch (refs/pull/N/merged) while the PR is still a draft thus making the build fail during import phase. Since drafts are (often) expected to fail, the daemon should just ignore PRs until they are marked as ready for review.

**Comment by doudou** [comment]
can't we test the head branch instead for drafts ?

I would find not running CI in drafts rather suboptimal.

**Comment by g-arjones** [comment]
Sounds good to me.. I just think that most people don't care about test results in drafts 

Testing HEAD is probably even easier to implement
