### ISSUE TITLE
Synchronize packages mainline heads on start

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#5]
When the daemon stays offline for too long it might lose push events and lose track of the build state. To mitigate this we could poll every package and compare the remote head with our local head, triggering a mainline build when appropriate.

**Comment by doudou** [comment]
I agree, a low-frequency poll to check for synchronization would make sense.

**Comment by g-arjones** [comment]
We don't fetch events anymore, we are actually doing the polling suggested here.
