### ISSUE TITLE
Daemon should recover from diverging trees

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#6]
We could do a force reset when an update fails

**Comment by doudou** [comment]
I think we should always do a force reset. What would be the downside ?

**Comment by g-arjones** [comment]
> What would be the downside ?

Not really a downside but a force reset without the update is a no-op

**Comment by doudou** [comment]
`update --force-reset` does update and then resets the local to the remote. Which is really what one wants in a CI.

**Comment by g-arjones** [comment]
Ah, didn't remember we had that already.. That's exactly what we want indeed.

Now, there's the extreme case of a commit that conflicts with a patch file. I don't have a plan for this one, do you?

**Comment by doudou** [comment]
> I don't have a plan for this one, do you?

This goes into the "buildconf error".
