### ISSUE TITLE
Trigger a build when a dependency is updated

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#61]
A simple way to implement this would be to generate a hash based on the details of the dependencies (head commit, base branch, draft status). This would also have the benefit of not having to store the overrides anymore.

**Comment by doudou** [comment]
I think the best way to handle all of this is to finally create a proper graph of all the (packages, pull request|mainline) pairs and trigger as needed whenever there is a change. It would make things a lot cleaner, and _in fine_ allow to have a single daemon for multiple workspaces (where the daemon loads information only from the installation manifest)

**Comment by g-arjones** [comment]
I don't understand why we need a dependency graph. As far as I can see, as soon as we remove the buildconf branch management (and start generating overrides in the build pipeline) having the daemon watch multiple workspaces would only be a matter of adding a "project" property to `PackageRepository` and loading the installation manifests. The current poller implementation already allows multiple packages to point to the same repository, the fact that they may belong to different workspaces doesn't really matter.

**Comment by g-arjones** [comment]
This is actually even simpler than I thought. It would probably take more time to fix the test suite than implementing what has to be implemented. I'll try to find some time to get this done.

I'm considering moving the git rest api abstraction layer to autoproj (including the CLI to set the keys) even if it's not going to be used there. Since we will be using this functionality in multiple plugins and there's no good way to have a plugin depend on a lib/plugin that isn't released as ruby gem I think that would be acceptable. @doudou Does that sound ok to you?

**Comment by doudou** [comment]
> Does that sound ok to you?

Actually, not so much, no. Just release that git-rest-api abstraction layer as a gem ? The plugin does not have to be, it can depend on it.

For devel, you can register both packages as plugins, it will work.
