### ISSUE TITLE
Daemon should detect changes in PR's body (overrides)

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj-daemon#8]
We can't get that through events.. Not sure if there is a workaround that actually makes sense

**Comment by doudou** [comment]
We could require that adding of removing dependencies is done through comments rather than by changing the text ?

**Comment by g-arjones** [comment]
That would be an option but kinda defeats the purpose of the neat checkboxes...

**Comment by g-arjones** [comment]
If we decided to do that I think I would rather just paste the overrides file as a comment in the PR and use some kind of hash tag for the daemon to pick it up

**Comment by g-arjones** [comment]
Alternatively, we could keep it as we do today (with the task list in the body) and use the hashtag just to trigger the daemon..

**Comment by doudou** [comment]
> Alternatively, we could keep it as we do today (with the task list in the body) and use the hashtag just to trigger the daemon..

Sounds like a plan.
